server:
  port: 8000 


spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
#      enabled: true
      routes:
        - id: content
          uri: ${URL_CONTENT:http://127.0.0.1:8001/}
          predicates:
            - Path=/
        - id: shortener
          uri: ${URL_SHORTENER:http://127.0.0.1:8002/}
          predicates:
            - Path=/create/**
          filters:
            - StripPrefix=1
