services:
  gateway:
    container_name: shortline-gateway
    build:
      context: ./gateway
      args:
        version: ${GATEWAY_APP_VERSION}
    image: ${GATEWAY_IMAGE_NAME}
    environment:
      URL_CONTENT: http://content:8001
      URL_SHORTENER: http://shortener:8002
    ports:
      - 8000:8000
    networks:
      - net-shortline

  content:
    container_name: shortline-content
    build:
      context: ./content
      args:
        version: ${CONTENT_APP_VERSION}
    image: ${CONTENT_IMAGE_NAME}
    ports:
      - 8001:8001
    networks:
      - net-shortline	  

  shortener:
    container_name: shortline-shortener
    build:
      context: ./shortener
      args:
        version: ${SHORTENER_APP_VERSION}
    image: ${SHORTENER_IMAGE_NAME}
    ports:
      - 8002:8002
    networks:
      - net-shortline

networks:
  net-shortline:
 